github.com:
    users:
        Marvin4200:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Marvin4200
