server:
  port: 2333
  address: 0.0.0.0

plugins:
  lavasrc:
    providers:
      - 'ytsearch:"%ISRC%"'
      - "ytsearch:%QUERY%"
    sources:
      spotify: true
      appleMusic: false
      deezer: false
      yandexMusic: false
    spotify:
      clientId: "REPLACE_WITH_SPOTIFY_CLIENT_ID"
      clientSecret: "REPLACE_WITH_SPOTIFY_CLIENT_SECRET"
      countryCode: "DE"
      playlistLoadLimit: 6
      albumLoadLimit: 2

lavalink:
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.1"
      repository: "https://maven.topi314.dev/releases"
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: false
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: false
      timescale: true
      tremolo: false
      vibrato: false
      distortion: false
      rotation: false
      channelMix: false
      lowPass: false

metrics:
  prometheus:
    enabled: false

logging:
  level:
    root: INFO
    lavalink: INFO
